services:
  # KeeperCheky Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: keepercheky-dev
    ports:
      - "8000:8000"
    volumes:
      - go-modules:/go/pkg/mod
      - ./data:/app/data
      - ./config:/app/config
      - media-test:/media:ro  # Read-only access to test media
    environment:
      - KEEPERCHEKY_APP_ENVIRONMENT=development
      - KEEPERCHEKY_APP_LOG_LEVEL=debug
      - KEEPERCHEKY_APP_DRY_RUN=true
      - KEEPERCHEKY_SERVER_PORT=8000
      - KEEPERCHEKY_DATABASE_TYPE=sqlite
      - KEEPERCHEKY_DATABASE_PATH=/app/data/dev.db
      # Services configuration
      - KEEPERCHEKY_SERVICES_RADARR_ENABLED=true
      - KEEPERCHEKY_SERVICES_RADARR_URL=http://radarr:7878
      - KEEPERCHEKY_SERVICES_RADARR_APIKEY=test-radarr-api-key-12345
      - KEEPERCHEKY_SERVICES_SONARR_ENABLED=true
      - KEEPERCHEKY_SERVICES_SONARR_URL=http://sonarr:8989
      - KEEPERCHEKY_SERVICES_SONARR_APIKEY=test-sonarr-api-key-12345
      - KEEPERCHEKY_SERVICES_JELLYFIN_ENABLED=true
      - KEEPERCHEKY_SERVICES_JELLYFIN_URL=http://jellyfin:8096
      - KEEPERCHEKY_SERVICES_JELLYFIN_APIKEY=test-jellyfin-api-key-12345
      - KEEPERCHEKY_SERVICES_JELLYSEERR_ENABLED=true
      - KEEPERCHEKY_SERVICES_JELLYSEERR_URL=http://jellyseerr:5055
      - KEEPERCHEKY_SERVICES_JELLYSEERR_APIKEY=test-jellyseerr-api-key-12345
    develop:
      watch:
        # Sync Go source code
        - path: ./cmd
          action: sync
          target: /app/cmd
        - path: ./internal
          action: sync
          target: /app/internal
        - path: ./pkg
          action: sync
          target: /app/pkg
        # Sync web files
        - path: ./web
          action: sync
          target: /app/web
        # Rebuild on go.mod changes
        - path: ./go.mod
          action: rebuild
        - path: ./go.sum
          action: rebuild
    networks:
      - keepercheky-net
    depends_on:
      - radarr
      - sonarr
      - jellyfin
      - jellyseerr
    restart: unless-stopped

  # Radarr - Movie Management
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - radarr-config:/config
      - media-test:/media
    ports:
      - "7878:7878"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Sonarr - TV Series Management
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - sonarr-config:/config
      - media-test:/media
    ports:
      - "8989:8989"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Jellyfin - Media Server
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - jellyfin-config:/config
      - media-test:/media:ro
    ports:
      - "8096:8096"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Jellyseerr - Request Management
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - "5055:5055"
    networks:
      - keepercheky-net
    restart: unless-stopped

volumes:
  go-modules:
  radarr-config:
  sonarr-config:
  jellyfin-config:
  jellyseerr-config:
  media-test:

networks:
  keepercheky-net:
    driver: bridge
