services:
  # KeeperCheky Application
  keepercheky:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: keepercheky-dev
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/keepercheky-go-modules:/go/pkg/mod
      - ./data:/app/data
      - ./config:/app/config
      - ./volumes/media-library:/media-library:ro  # Read-only access to test media
    environment:
      - KEEPERCHEKY_APP_ENVIRONMENT=development
      - KEEPERCHEKY_APP_LOG_LEVEL=debug
      - KEEPERCHEKY_APP_DRY_RUN=true
      - KEEPERCHEKY_SERVER_PORT=8000
      - KEEPERCHEKY_DATABASE_TYPE=sqlite
      - KEEPERCHEKY_DATABASE_PATH=/app/data/dev.db
      # Services configuration
      - KEEPERCHEKY_SERVICES_RADARR_ENABLED=true
      - KEEPERCHEKY_SERVICES_RADARR_URL=http://radarr:7878
      - KEEPERCHEKY_SERVICES_RADARR_APIKEY=test-radarr-api-key-12345
      - KEEPERCHEKY_SERVICES_SONARR_ENABLED=true
      - KEEPERCHEKY_SERVICES_SONARR_URL=http://sonarr:8989
      - KEEPERCHEKY_SERVICES_SONARR_APIKEY=test-sonarr-api-key-12345
      - KEEPERCHEKY_SERVICES_JELLYFIN_ENABLED=true
      - KEEPERCHEKY_SERVICES_JELLYFIN_URL=http://jellyfin:8096
      - KEEPERCHEKY_SERVICES_JELLYFIN_APIKEY=test-jellyfin-api-key-12345
      - KEEPERCHEKY_SERVICES_JELLYSEERR_ENABLED=true
      - KEEPERCHEKY_SERVICES_JELLYSEERR_URL=http://jellyseerr:5055
      - KEEPERCHEKY_SERVICES_JELLYSEERR_APIKEY=test-jellyseerr-api-key-12345
      # qBittorrent configuration (seeding validation)
      - KEEPERCHEKY_SERVICES_QBITTORRENT_ENABLED=true
      - KEEPERCHEKY_SERVICES_QBITTORRENT_URL=http://qbittorrent:8080
      - KEEPERCHEKY_SERVICES_QBITTORRENT_USERNAME=admin
      - KEEPERCHEKY_SERVICES_QBITTORRENT_PASSWORD=adminadmin
      # Bazarr configuration (subtitle preservation)
      - KEEPERCHEKY_SERVICES_BAZARR_ENABLED=true
      - KEEPERCHEKY_SERVICES_BAZARR_URL=http://bazarr:6767
      - KEEPERCHEKY_SERVICES_BAZARR_APIKEY=test-bazarr-api-key-12345
      # Jellystat configuration (playback statistics)
      - KEEPERCHEKY_SERVICES_JELLYSTAT_ENABLED=true
      - KEEPERCHEKY_SERVICES_JELLYSTAT_URL=http://jellystat:3000
      - KEEPERCHEKY_SERVICES_JELLYSTAT_APIKEY=test-jellystat-api-key-12345
    develop:
      watch:
        # Sync Go source code
        - path: ./cmd
          action: sync
          target: /app/cmd
        - path: ./internal
          action: sync
          target: /app/internal
        - path: ./pkg
          action: sync
          target: /app/pkg
        # Sync web files
        - path: ./web
          action: sync
          target: /app/web
        # Rebuild on go.mod changes
        - path: ./go.mod
          action: rebuild
        - path: ./go.sum
          action: rebuild
    networks:
      - keepercheky-net
    depends_on:
      - radarr
      - sonarr
      - jellyfin
      - jellyseerr
      - qbittorrent
      - bazarr
      - jellystat
      - jellystat-db
    restart: unless-stopped

  # Radarr - Movie Management
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./volumes/radarr-config:/config
      - ./volumes/media-library:/media-library
    ports:
      - "7878:7878"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Sonarr - TV Series Management
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./volumes/sonarr-config:/config
      - ./volumes/media-library:/media-library
    ports:
      - "8989:8989"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Jellyfin - Media Server
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./volumes/jellyfin-config:/config
      - ./volumes/media-library:/media-library:ro
    ports:
      - "8096:8096"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Jellyseerr - Request Management
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./volumes/jellyseerr-config:/app/config
    ports:
      - "5055:5055"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # qBittorrent - Torrent Client (Seeding validation)
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - ./volumes/qbittorrent-config:/config
      - ./volumes/media-library:/media-library
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Bazarr - Subtitle Management (Preserve subtitles before deletion)
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./volumes/bazarr-config:/config
      - ./volumes/media-library:/media-library
    ports:
      - "6767:6767"
    networks:
      - keepercheky-net
    restart: unless-stopped

  # Jellystat - Jellyfin Statistics & Playback Tracking
  jellystat-db:
    image: postgres:15-alpine
    container_name: jellystat-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=keepercheky-dev-password
      - POSTGRES_DB=jfstat
    volumes:
      - jellystat-db:/var/lib/postgresql/data
    networks:
      - keepercheky-net
    restart: unless-stopped

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=keepercheky-dev-password
      - POSTGRES_IP=jellystat-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=jfstat
      - JWT_SECRET=keepercheky-jellystat-secret-dev
      - TZ=Europe/Madrid
    volumes:
      - ./volumes/jellystat-config:/app/backend/backup-data
    ports:
      - "3000:3000"
    networks:
      - keepercheky-net
    depends_on:
      - jellyfin
      - jellystat-db
    restart: unless-stopped

volumes:
  jellystat-db:

networks:
  keepercheky-net:
    driver: bridge
