services:
  keepercheky:
    image: ghcr.io/carcheky/keepercheky:develop # or latest
    container_name: keepercheky-quickstart
    # Run container process as host user so mounted volumes are writable
    user: "${PUID:-1000}:${PGID:-1000}"
    restart: unless-stopped
    ports:
      - "${KEEPERCHEKY_PORT:-8780}:8000"
    volumes:
      - ./volumes/keepercheky-data:/app/data
      - ./volumes/keepercheky-config:/app/config
      - ./logs:/app/logs
      - ${MEDIA_PATH:-/path/to/media}:/media-library:ro
    environment:
      # Server Configuration
      - KEEPERCHEKY_SERVER_PORT=8000
      - KEEPERCHEKY_SERVER_HOST=0.0.0.0
      
      # Database Configuration
      - KEEPERCHEKY_DATABASE_TYPE=${DB_TYPE:-sqlite}
      - KEEPERCHEKY_DATABASE_PATH=${DB_PATH:-/app/data/keepercheky.db}
      
      # Application Settings
      - KEEPERCHEKY_APP_DRY_RUN=${APP_DRY_RUN:-true}
      - KEEPERCHEKY_APP_LOG_LEVEL=${APP_LOG_LEVEL:-info}
      - KEEPERCHEKY_APP_LEAVING_SOON_DAYS=${APP_LEAVING_SOON_DAYS:-7}
      
      # Radarr Configuration
      - KEEPERCHEKY_CLIENTS_RADARR_ENABLED=${RADARR_ENABLED:-false}
      - KEEPERCHEKY_CLIENTS_RADARR_URL=${RADARR_URL:-}
      - KEEPERCHEKY_CLIENTS_RADARR_API_KEY=${RADARR_API_KEY:-}
      
      # Sonarr Configuration
      - KEEPERCHEKY_CLIENTS_SONARR_ENABLED=${SONARR_ENABLED:-false}
      - KEEPERCHEKY_CLIENTS_SONARR_URL=${SONARR_URL:-}
      - KEEPERCHEKY_CLIENTS_SONARR_API_KEY=${SONARR_API_KEY:-}
      
      # Jellyfin Configuration
      - KEEPERCHEKY_CLIENTS_JELLYFIN_ENABLED=${JELLYFIN_ENABLED:-false}
      - KEEPERCHEKY_CLIENTS_JELLYFIN_URL=${JELLYFIN_URL:-}
      - KEEPERCHEKY_CLIENTS_JELLYFIN_API_KEY=${JELLYFIN_API_KEY:-}
      
      # Jellyseerr Configuration
      - KEEPERCHEKY_CLIENTS_JELLYSEERR_ENABLED=${JELLYSEERR_ENABLED:-false}
      - KEEPERCHEKY_CLIENTS_JELLYSEERR_URL=${JELLYSEERR_URL:-}
      - KEEPERCHEKY_CLIENTS_JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY:-}
      
      # qBittorrent Configuration
      - KEEPERCHEKY_CLIENTS_QBITTORRENT_ENABLED=${QBITTORRENT_ENABLED:-false}
      - KEEPERCHEKY_CLIENTS_QBITTORRENT_URL=${QBITTORRENT_URL:-}
      - KEEPERCHEKY_CLIENTS_QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME:-}
      - KEEPERCHEKY_CLIENTS_QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD:-}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - keepercheky-network

networks:
  keepercheky-network:
    name: keepercheky-quickstart-network
