version: '3.8'

services:
  keepercheky:
    image: ghcr.io/carcheky/keepercheky:latest
    container_name: keepercheky-quickstart
    restart: unless-stopped
    ports:
      - "${KEEPERCHEKY_PORT:-8080}:8000"
    volumes:
      # Configuration
      - ./config:/config
      # Database persistence
      - ./data:/data
      # Media library (read-only recommended)
      - ${MEDIA_PATH:-/path/to/media}:/media:ro
      # Logs
      - ./logs:/logs
    environment:
      # Server Configuration
      - SERVER_PORT=8000
      - SERVER_HOST=0.0.0.0
      
      # Database Configuration
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_PATH=${DB_PATH:-/data/keepercheky.db}
      
      # Application Settings
      - APP_DRY_RUN=${APP_DRY_RUN:-true}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-info}
      - APP_LEAVING_SOON_DAYS=${APP_LEAVING_SOON_DAYS:-7}
      
      # Radarr Configuration
      - RADARR_ENABLED=${RADARR_ENABLED:-false}
      - RADARR_URL=${RADARR_URL:-}
      - RADARR_API_KEY=${RADARR_API_KEY:-}
      
      # Sonarr Configuration
      - SONARR_ENABLED=${SONARR_ENABLED:-false}
      - SONARR_URL=${SONARR_URL:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}
      
      # Jellyfin Configuration
      - JELLYFIN_ENABLED=${JELLYFIN_ENABLED:-false}
      - JELLYFIN_URL=${JELLYFIN_URL:-}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY:-}
      
      # Jellyseerr Configuration
      - JELLYSEERR_ENABLED=${JELLYSEERR_ENABLED:-false}
      - JELLYSEERR_URL=${JELLYSEERR_URL:-}
      - JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY:-}
      
      # qBittorrent Configuration
      - QBITTORRENT_ENABLED=${QBITTORRENT_ENABLED:-false}
      - QBITTORRENT_URL=${QBITTORRENT_URL:-}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME:-}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD:-}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - keepercheky-network

networks:
  keepercheky-network:
    name: keepercheky-quickstart-network
