name: Native images

on:
  push:
    paths:
      - src/**
      - buildSrc/**
      - .github/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
    tags:
      - '**'
    branches:
      - 'develop'
      - 'main'

  pull_request:
    paths:
      - src/**
      - buildSrc/**
      - .github/**
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build-native-x86:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.1.0

      - name: Build Native OCI Image
        run: ./gradlew bootBuildImage --publishImage --imagePlatform linux/amd64
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          IMAGE_TYPE: "native"
          TARGET_PLATFORM: "amd64"

  build-native-aarch64:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.1.0

      - name: Build Native ARM64 OCI Image
        run: ./gradlew bootBuildImage --publishImage --imagePlatform linux/arm64
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          IMAGE_TYPE: "native"
          TARGET_PLATFORM: "arm64"

  combine-images:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-native-x86, build-native-aarch64]
    steps:

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export branch name
        uses: mad9000/actions-find-and-replace-string@5
        id: branch_name
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'

      - name: Extract version without v prefix
        id: version_number
        run: |
          VERSION="${{ steps.branch_name.outputs.value }}"
          # Remove 'v' prefix if it exists
          VERSION_NO_V="${VERSION#v}"
          echo "value=$VERSION_NO_V" >> $GITHUB_OUTPUT

      - name: Combine native images into single manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/janitorr-native:${{ steps.branch_name.outputs.value }}
            ${{ (startsWith(github.ref, 'refs/tags/v') && format('ghcr.io/{0}/janitorr-native:latest', github.repository_owner)) || '' }}
            ${{ (startsWith(github.ref, 'refs/tags/v') && format('ghcr.io/{0}/janitorr-native:{1}', github.repository_owner, steps.version_number.outputs.value)) || '' }}
          sources: |
            ghcr.io/${{ github.repository_owner }}/janitorr-native:amd64-${{ steps.branch_name.outputs.value }}
            ghcr.io/${{ github.repository_owner }}/janitorr-native:arm64-${{ steps.branch_name.outputs.value }}